version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCatCont
    restart: always
    environment:
      - POSTGRES_DB=cat-site
      - POSTGRES_USER=cat-user
      - POSTGRES_PASSWORD=cat-pass
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local