spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/cat-site
    username: cat-user
    password: cat-pass
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/cat-site
    user: cat-user
    password: cat-pass
  sql:
    init:
      mode: always